# spring profile properties
spring.profiles:
  active: default

# server properties
server:
  port: 9999
  context-path: /cathub

# thymeleaf properties
spring:
  thymeleaf:
    cache: false
    
# logging properties
logging:
  level:
    com.example: DEBUG

# app properties
app:
  data:
    commons:
      default-page-size: 30

# api properties
api:
  github:
    base-uri: "https://api.github.com"
    search:
      issues: ${api.github.base-uri}/search/issues
      repositories: ${api.github.base-uri}/search/repositories
      max-page-size: 100
      max-element-size: 1000
      