# spring profile properties
spring.profiles:
  active: default

# server properties
server:
  port: 9999
  context-path: /cathub

# thymeleaf settings
spring:
  thymeleaf:
    cache: false
     
# logging properties
logging:
  level:
    com.example: DEBUG

# app properties
app:
  data:
    commons:
      default-page-size: 100

# api properties
api:
  github:
    search:
      issues: https://api.github.com/search/issues
