# spring profile properties
spring.profiles:
  active: default

# server properties
server:
  port: 9999
  context-path: /cathub

# thymeleaf settings
spring:
  thymeleaf:
    cache: false
    excluded-view-names : issuesExcelView
    
# logging properties
logging:
  level:
    org.springframework: WARN
    com.example: DEBUG

# app properties
app:
  data:
    commons:
      default-page-size: 30

# api properties
api:
  github:
    search:
      issues: https://api.github.com/search/issues
      max-page-size: 100
      limit-element-size: 1000
      